name: arogyaconnect
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.9.0'   # Adjust to your installed SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

# 👇 flutter section for assets & design
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

# 👇 config for launcher icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
